### PR TITLE
Implemented natural, integer, real, and scientific number options

### PR DESCRIPTION
**Pull request by billdenney**
In this pull request, I've implemented options where the user can choose what type of number for the interpretation.  It (unfortunately) was a significant rewrite of the naturalorder function.

All of the original tests pass with this pull request, and I added tests for the new functionality.

This is discussed in #7.

### CODE REVIEW

**Comment by kos59125** [comment]
Thx. I'm going to check it.

**Comment by billdenney** [comment]
Hello,  I recently found a need to use sorting like that in the PR.

I wanted to check on the PR and see if you would be willing to commit it and push it to CRAN?

**Comment by billdenney** [comment]
@kos59125, I recently needed this again for a project.  Is this something that you would be interested in putting into your package?

**Comment by kos59125** [comment]
I'm sorry for I did miss your comments but I would like to retire from naturalsort package. The package is not good in performance and I have no time to improve it.

You may want to use or contribute to [gtools::mixedsort](https://www.rdocumentation.org/packages/gtools/versions/3.5.0/topics/mixedsort) package. I don't try the package, but it seems to be a substitute for naturalsort.

**Comment by billdenney** [comment]
OK, thanks for the info.

**Pull request closed without merging**
